# Generated by Django 4.2.3 on 2024-04-22 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('News', '0002_news_news_date_news_news_desc_news_news_img_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='news_date',
            field=models.DateField(default='2024-05-17'),
        ),
    ]
