# Generated by Django 4.2.3 on 2024-04-29 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('News', '0007_alter_news_news_desc_alter_news_news_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='news_img',
            field=models.ImageField(default='None', upload_to='Media/news'),
        ),
    ]
