# Generated by Django 4.2.3 on 2024-04-29 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('News', '0008_alter_news_news_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='news_desc',
            field=models.TextField(default='', max_length=1500),
        ),
    ]
