# Generated by Django 4.2.3 on 2024-05-09 10:45

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('Customer', '0002_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='email_token',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.AddField(
            model_name='customer',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='profile',
        ),
    ]
