# Generated by Django 4.2.3 on 2024-05-05 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0007_cart_cartitems'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartitems',
            old_name='cart',
            new_name='cartF',
        ),
        migrations.RenameField(
            model_name='cartitems',
            old_name='product',
            new_name='productF',
        ),
        migrations.AddField(
            model_name='cartitems',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
    ]
