# Generated by Django 4.2.3 on 2024-05-05 22:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0008_rename_cart_cartitems_cartf_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='user',
            new_name='Customer',
        ),
    ]
