# Generated by Django 4.2.3 on 2024-05-09 23:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Customer', '0003_customer_email_token_customer_is_verified_and_more'),
        ('Shop', '0012_order_details_order_email_token_order_payment_method'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='order',
            new_name='orderModel',
        ),
    ]
